### ISSUE TITLE
Problem with building system

### ISSUE THREAD

**Issue by rpgoldman** [panda-planner-dev/VerificationAsPlanning#1]
I tried to build this using

    cmake .
    make

But I get this error:

```
In file included from /Users/rpg/src/pandaPIpgrRepairVerify/verifier/util/execution.cpp:1:
/Users/rpg/src/pandaPIpgrRepairVerify/verifier/util/execution.h:4:10: fatal error: 'Model.h' file not found
#include "Model.h"
         ^~~~~~~~~
1 error generated.
make[2]: *** [verifier/CMakeFiles/util.dir/util/execution.cpp.o] Error 1
make[1]: *** [verifier/CMakeFiles/util.dir/all] Error 2
make: *** [all] Error 2
```

I suspect that this means there's some include file configuration that I am missing, but I am afraid I am not a `cmake` user, so I don't know how to fix this.

**Comment by rpgoldman** [comment]
I have a *partial* fix for this. The `CMakeLists.txt` file seems to rely on an out-of-date variable name, and is also missing code for finding the boost libraries. You can find a patch file as a GitHub gist [here](https://gist.github.com/rpgoldman/60b86b45983191b46dfd4f8a512f7898)

**Comment by galvusdamor** [comment]
I've just verified that this problem also appears under Linux -- and it does. @rpgoldman's patch solves this issue. I have added it to the master.
